[package]
name = "cratesfyi"
version = "0.6.0"
authors = ["Onur Aslan <onuraslan@gmail.com>"]
readme = "README.md"
license = "MIT"
repository = "https://github.com/rust-lang/docs.rs"
build = "build.rs"

[dependencies]
log = "0.4"
rustc-serialize = "0.3"
regex = "1"
clap = "2"
crates-index-diff = "7"
time = "0.1"
reqwest = "0.9"
semver = "0.9"
slug = "=0.1.1"
env_logger = "0.7"
r2d2 = "0.8"
r2d2_postgres = "0.14"
url = "1.4"
badge = { version = "0", path = "src/web/badge" }
failure = "0.1.3"
comrak = { version = "0.7", default-features = false }
toml = "0.5"
html5ever = "0.24"
schemamama = "0.3"
schemamama_postgres = "0.2"
rusoto_s3 = "0.40"
rusoto_core = "0.40"
rusoto_credential = "0.40"
futures = "0.1"
tokio = "0.1"
systemstat = "0.1.4"
prometheus = { version = "0.7.0", default-features = false }
lazy_static = "1.0.0"
rustwide = "0.5"
tempdir = "0.3"
mime_guess = "2"

# iron dependencies
iron = "0.5"
router = "0.5"
handlebars-iron = "0.22"
params = "0.8"
staticfile = { version = "0.4", features = [ "cache" ] }

[target.'cfg(not(windows))'.dependencies]
libc = "0.2"

[target.'cfg(windows)'.dependencies]
path-slash = "0.1.1"

[dependencies.postgres]
version = "0.15"
features = [ "with-time", "with-rustc-serialize" ]

[dev-dependencies]
once_cell = "1.2.0"
kuchiki = "0.8"

[build-dependencies]
time = "0.1"
git2 = { version = "0.13", default-features = false }
sass-rs = "0.2"

[[bin]]
name = "cratesfyi"
test = false
doc = false
