[package]
name = "docs-rs"
version = "0.6.0"
authors = ["Onur Aslan <onuraslan@gmail.com>", "The Rust Project Developers"]
readme = "README.md"
license = "MIT"
repository = "https://github.com/rust-lang/docs.rs"
build = "build.rs"
edition = "2018"

[workspace]
exclude = [
    "ignored",
    ".workspace",
    ".rustwide-docker",
]

[dependencies]
log = "0.4"
regex = "1"
structopt = "0.3"
crates-index = "0.15.1"
crates-index-diff = "7"
reqwest = { version = "0.10.6", features = ["blocking", "json"] } # TODO: Remove blocking when async is ready
semver = { version = "0.9", features = ["serde"] }
slug = "=0.1.1"
env_logger = "0.7"
r2d2 = "0.8"
r2d2_postgres = "0.16"
# iron needs url@1, but it reexports it as iron::url, so we can start using
# url@2 for other usecases
url = { version = "2.1.1", features = ["serde"] }
badge = { path = "src/web/badge" }
docsrs-metadata = { path = "metadata" }
backtrace = "0.3"
failure = { version = "0.1.3", features = ["backtrace"] }
comrak = { version = "0.8", default-features = false }
toml = "0.5"
schemamama = "0.3"
schemamama_postgres = "0.3"
systemstat = "0.1.4"
prometheus = { version = "0.9.0", default-features = false }
rustwide = "0.10.0"
mime_guess = "2"
dotenv = "0.15"
zstd = "0.5"
git2 = { version = "0.13.6", default-features = false }
path-slash = "0.1.3"
once_cell = { version = "1.4.0", features = ["parking_lot"] }
base64 = "0.12.1"
strum = { version = "0.18.0", features = ["derive"] }
lol_html = "0.2"

# Async
tokio = { version = "0.2.22", features = ["rt-threaded"] }
futures-util = "0.3.5"
rusoto_s3 = "0.45.0"
rusoto_core = "0.45.0"
rusoto_credential = "0.45.0"

# Data serialization and deserialization
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

# iron dependencies
iron = "0.5"
router = "0.5"
staticfile = { version = "0.4", features = ["cache"] }
tempfile = "3.1.0"

# Templating
tera = { version = "1.5.0", features = ["builtins"] }
walkdir = "2"

# Template hot-reloading
arc-swap = "0.4.6"
notify = "4.0.15"

# Date and Time utilities
chrono = { version = "0.4.11", features = ["serde"] }
time = "0.1" # TODO: Remove once `iron` is removed

[dependencies.postgres]
version = "0.17"
features = ["with-chrono-0_4", "with-serde_json-1"]

[target.'cfg(target_os = "linux")'.dependencies]
# Process information
procfs = "0.7"

[dev-dependencies]
criterion = "0.3"
kuchiki = "0.8"
rand = "0.7.3"

[build-dependencies]
time = "0.1"
git2 = { version = "0.13", default-features = false }
sass-rs = "0.2.2"

[[bench]]
name = "html_parsing"
harness = false

[[bench]]
name = "compression"
harness = false

[[bin]]
name = "cratesfyi"
test = false
doc = false
