[package]
name = "cratesfyi"
version = "0.2.1"
authors = ["Onur Aslan <onuraslan@gmail.com>"]
readme = "README.md"
license = "MIT"
repository = "https://github.com/onur/cratesfyi"
build = "build.rs"

[dependencies]
log = "0.3"
rustc-serialize = "0.3"
regex = "0.1"
postgres = { version = "0.11", features = [ "time", "rustc-serialize" ] }
clap = "2.14"
time = "0.1"
hyper = "0.9"
semver = "0.4"
slug = "=0.1.1"
env_logger = "0.3"
git2 = "0.4"
magic = "0.12"
iron = "0.3.1"
router = "0.1.1"
staticfile = { version = "0.2.0", features = [ "cache" ] }
handlebars-iron = "=0.15.2"
r2d2 = "0.7.0"
r2d2_postgres = "0.10.1"
url = "1.2"
params = "0.2"
libc = "0.2"
hoedown = "5.0"
badge = { version = "0", path = "src/web/badge" }
error-chain = "0.5"

[dependencies.cargo]
git = "https://github.com/rust-lang/cargo.git"
rev = "c917e94b419ce62760c0a6fdcf90ff0d7d1d5cdb"

[dev-dependencies]
tempdir = "0.3"

[build-dependencies]
time = "0.1"
sass-rs = "0.0.18"

[[bin]]
name = "cratesfyi"
test = false
doc = false
