[package]
name = "cratesfyi"
version = "0.2.0"
authors = ["Onur Aslan <onuraslan@gmail.com>"]
readme = "README.md"
license = "MIT"
repository = "https://github.com/onur/cratesfyi"
build = "build.rs"

[dependencies]
log = "0.3"
rustc-serialize = "0.3"
regex = "0.1"
postgres = { version = "^0.11", features = [ "time", "rustc-serialize" ] }
clap = "2.5.2"
time = "0.1"
hyper = "0.9.7"
semver = "0.2.2"
slug = "^0.1.1"
env_logger = "0.3"
git2 = "0.4"
magic = "^0.10.0"
iron = "0.3.0"
router = "0.1.1"
staticfile = { version = "0.2.0", features = [ "cache" ] }
handlebars-iron = "0.15.2"
pulldown-cmark = "0.0.8"
r2d2 = "0.7.0"
r2d2_postgres = "0.10.1"
url = "1.1.1"
params = "0.2.2"
libc = "0.2"

[dependencies.badge]
path = "src/web/badge"
version = "0"

[dependencies.cargo]
git = "https://github.com/rust-lang/cargo.git"
rev = "ffa147d393037fd5632cd8c9d048b5521d70ab4c"

[dev-dependencies]
tempdir = "0.3"

[build-dependencies]
time = "0.1"

[[bin]]
name = "cratesfyi"
test = false
doc = false
