[package]
name = "cratesfyi"
version = "0.6.0"
authors = ["Onur Aslan <onuraslan@gmail.com>"]
readme = "README.md"
license = "MIT"
repository = "https://github.com/rust-lang/docs.rs"
build = "build.rs"
edition = "2018"

[dependencies]
log = "0.4"
rustc-serialize = "0.3"
regex = "1"
clap = "2"
crates-index-diff = "4"
git2 = "0.7"
time = "0.1"
reqwest = "0.9"
semver = "0.9"
slug = "=0.1.1"
env_logger = "0.6"
magic = "0.12"
r2d2 = "0.8"
r2d2_postgres = "0.14"
url = "1.4"
libc = "0.2"
badge = { version = "0", path = "src/web/badge" }
failure = "0.1.3"
comrak = { version = "0.3", default-features = false }
toml = "0.4"
html5ever = "0.22"
cargo = { git = "https://github.com/rust-lang/cargo.git" }
schemamama = "0.3"
schemamama_postgres = "0.2"


# iron dependencies
iron = "0.5"
router = "0.5"
handlebars-iron = "0.22"
params = "0.6"
staticfile = { version = "0.4", features = [ "cache" ] }

[dependencies.postgres]
version = "0.15"
features = [ "with-time", "with-rustc-serialize" ]

[dev-dependencies]
tempdir = "0.3"

[build-dependencies]
time = "0.1"
git2 = "0.7"
sass-rs = "0.2"

[[bin]]
name = "cratesfyi"
test = false
doc = false
