version: "3"
services:
    web:
        build:
            context: .
            dockerfile: ./dockerfiles/Dockerfile
        depends_on:
            - db
            - s3
        ports:
            - "3000:3000"
        # for metrics
        expose: ["3000"]
        volumes:
            - "/var/run/docker.sock:/var/run/docker.sock"
            - ".rustwide-docker:/opt/docsrs/rustwide"
            - "cratesio-index:/opt/docsrs/prefix/crates.io-index"
        environment:
            CRATESFYI_RUSTWIDE_WORKSPACE: /opt/docsrs/rustwide
            CRATESFYI_DATABASE_URL: postgresql://cratesfyi:password@db
            S3_ENDPOINT: http://s3:9000
            AWS_ACCESS_KEY_ID: cratesfyi
            AWS_SECRET_ACCESS_KEY: secret_key
        env_file:
            - .env
    db:
        build:
            context: ./dockerfiles
            dockerfile: ./Dockerfile-postgres
        volumes:
            - postgres-data:/var/lib/postgresql/data
        environment:
            POSTGRES_USER: cratesfyi
            POSTGRES_PASSWORD: password
        ports:
            - "5432:5432"
    s3:
        image: minio/minio
        entrypoint: >
            /bin/sh -c "
                mkdir -p /data/rust-docs-rs;
                minio server /data;
            "
        ports:
            - "9000:9000"
        volumes:
            - minio-data:/data
        environment:
            MINIO_ACCESS_KEY: cratesfyi
            MINIO_SECRET_KEY: secret_key
    prometheus:
        build:
            context: ./dockerfiles
            dockerfile: ./Dockerfile-prometheus
        ports:
            - "9090:9090"
volumes:
    postgres-data: {}
    minio-data: {}
    cratesio-index: {}
