[package]
name = "badge"
version = "0.2.0"
authors = ["Onur Aslan <onur@onur.im>"]
documentation = "https://docs.rs/badge"
edition = "2018"
license-file = "LICENSE"
repository = "https://github.com/rust-lang/docs.rs"
description = "Simple badge generator"

[lib]
path = "badge.rs"

[dependencies]
base64 = "0.9.0"
rusttype = "0.7"
