[package]
name = "badge"
version = "0.2.0"
description = "Simple badge generator"
authors = ["Onur Aslan <onur@onur.im>"]
license-file = "LICENSE"
repository = "https://github.com/rust-lang/docs.rs"
documentation = "https://docs.rs/badge"
edition = "2018"

[dependencies]
base64 = "0.12.0"
rusttype = "0.8.2"
