[package]
name = "metadata"
version = "0.1.0"
authors = ["Joshua Nelson <jyn514@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
path = "lib.rs"

[dependencies]
toml = { version = "0.5", default-features = false }
thiserror = "1"

[package.metadata.docs.rs]
rustdoc-args = ["--document-private-items"]
