name: CI

on: [push, pull_request]

env:
  RUST_BACKTRACE: 1

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - id: install
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: install
          args: cargo-sweep

      - name: Cache directories
        uses: actions/cache@v1
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/bin
            ~/.cargo/git
          key: cargo-dirs-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: cargo-dirs-
      - name: Cache build
        uses: actions/cache@v1
        with:
          path: target
          key: cargo-build-${{ steps.install.outputs.rustc_hash }}-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            cargo-build-${{ steps.install.outputs.rustc_hash }}-
            cargo-build-

      - name: Register artifacts
        uses: actions-rs/cargo@v1
        with:
          command: sweep
          args: --stamp

      - name: Launch postgres and min.io
        run: |
          cp .env.sample .env
          . .env
          mkdir -p ${CRATESFYI_PREFIX}/public-html
          docker-compose up -d db s3
          # Give the database enough time to start up
          sleep 5
          # Make sure the database is actually working
          psql "${CRATESFYI_DATABASE_URL}"

      - name: Build
        run: cargo build --locked

      - name: Test
        run: cargo test --locked -- --test-threads=1

      - name: Clean up the database
        run: docker-compose down --volumes

      - name: Clean unused artifacts
        uses: actions-rs/cargo@v1
        with:
          command: sweep
          args: --file

  fmt:
    name: Rustfmt
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - id: install
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          components: rustfmt

      - uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: -- --check

  clippy:
    name: Clippy
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - id: install
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          components: clippy
      - uses: actions-rs/cargo@v1
        with:
          command: install
          args: cargo-sweep

      - name: Cache directories
        uses: actions/cache@v1
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/bin
            ~/.cargo/git
          key: cargo-dirs-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: cargo-dirs-
      - name: Cache build
        uses: actions/cache@v1
        with:
          path: target
          key: cargo-build-${{ steps.install.outputs.rustc_hash }}-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            cargo-build-${{ steps.install.outputs.rustc_hash }}-
            cargo-build-

      - name: Register artifacts
        uses: actions-rs/cargo@v1
        with:
          command: sweep
          args: --stamp

      - uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --locked -- -D warnings

      - name: Clean unused artifacts
        uses: actions-rs/cargo@v1
        with:
          command: sweep
          args: --file
