name: CI

on: [push, pull_request]

env:
  RUST_BACKTRACE: 1

jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [macos-latest, ubuntu-latest]

    steps:
      - uses: actions/checkout@master
      - id: install
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - uses: Swatinem/rust-cache@v1

      - uses: actions-rs/cargo@v1
        with:
          command: install
          args: cargo-sweep

      - name: Register artifacts
        uses: actions-rs/cargo@v1
        with:
          command: sweep
          args: --stamp

      - name: installing docker
        uses: docker-practice/actions-setup-docker@master
        if: ${{ matrix.os == 'macos-latest' }}

      - name: Launch postgres and min.io
        run: |
          cp .env.sample .env
          . .env
          mkdir -p ${CRATESFYI_PREFIX}/public-html
          docker-compose up -d db s3
          # Give the database enough time to start up
          sleep 5
          # Make sure the database is actually working
          psql "${CRATESFYI_DATABASE_URL}"

      - name: Build
        run: cargo build --workspace --locked

      - name: Test
        run: cargo test --workspace --locked

      - name: Clean up the database
        run: docker-compose down --volumes

      - name: Clean unused artifacts
        uses: actions-rs/cargo@v1
        with:
          command: sweep
          args: --file

  fmt:
    name: Rustfmt
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - id: install
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          components: rustfmt

      - uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: -- --check

  clippy:
    name: Clippy
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - id: install
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          components: clippy

      - uses: Swatinem/rust-cache@v1

      - uses: actions-rs/cargo@v1
        with:
          command: install
          args: cargo-sweep

      - name: Register artifacts
        uses: actions-rs/cargo@v1
        with:
          command: sweep
          args: --stamp

      - uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --all-targets --workspace --locked -- -D warnings

      - name: Clean unused artifacts
        uses: actions-rs/cargo@v1
        with:
          command: sweep
          args: --file
