name: Dependencies

on:
  push:
  pull_request:
    paths:
      - "**/Cargo.toml"
      - "**/Cargo.lock"

jobs:
  cargo_bloat:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - id: install
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Cache directories
        uses: actions/cache@v1
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/bin
            ~/.cargo/git
          key: cargo-deps-dirs-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: cargo-deps-dirs-
      - name: Cache build
        uses: actions/cache@v1
        with:
          path: target
          key: cargo-build-${{ steps.install.outputs.rustc_hash }}-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            cargo-deps-build-${{ steps.install.outputs.rustc_hash }}-
            cargo-deps-build-
      - uses: actions-rs/cargo@v1
        with:
          command: install
          args: cargo-sweep

      - name: Register artifacts
        uses: actions-rs/cargo@v1
        with:
          command: sweep
          args: --stamp

      - name: Run cargo bloat
        uses: orf/cargo-bloat-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Clean unused artifacts
        uses: actions-rs/cargo@v1
        with:
          command: sweep
          args: --file
